# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: github-action-config-levels
  description: GitHub Action that create a configuration consisting of configuration files of different levels
  homepage: https://cloudposse.com/accelerate
  topics: ""

